spring.application.name=auth-microservices
server.port=8081

keycloak.auth-server-url=http://localhost:8080
keycloak.realm=e-learning-realm
keycloak.client-id=e-learning
keycloak.client-secret=IGg4xa5pZNzud6ZoNkFXYGIaiwJNM3mr
keycloak.admin.username=admin
keycloak.admin.password=0000
